schemaVersion: 1
enabledWorkflows:
  - coverage
  - debugging
  - device
  - logging
  - macos
  - project-discovery
  - project-scaffolding
  - simulator
  - simulator-management
  - swift-package
  - ui-automation
  - utilities
  - xcode-ide
sessionDefaults:
  workspacePath: ./dimasike-apps.xcworkspace
  derivedDataPath: ./DerivedData
  preferXcodebuild: true
